// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProiectDAW.data;

namespace ProiectDAW.Migrations
{
    [DbContext(typeof(context))]
    [Migration("20220126175200_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProiectDAW.Models.AdreseAngajati", b =>
                {
                    b.Property<int>("IdAdresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdAngajat")
                        .HasColumnType("int");

                    b.Property<string>("Oras")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tara")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAdresa");

                    b.ToTable("Adrese");
                });

            modelBuilder.Entity("ProiectDAW.Models.Departamente", b =>
                {
                    b.Property<int>("IdDepartament")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NumeDepartament")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDepartament");

                    b.ToTable("Departamente");
                });

            modelBuilder.Entity("ProiectDAW.Models.Proiecte", b =>
                {
                    b.Property<int>("IdProiect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DetaliiProiect")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProiect");

                    b.ToTable("Proiecte");
                });

            modelBuilder.Entity("ProiectDAW.Models.ProiecteAngajati", b =>
                {
                    b.Property<int>("IdProiect")
                        .HasColumnType("int");

                    b.Property<int>("IdAngajat")
                        .HasColumnType("int");

                    b.HasKey("IdProiect", "IdAngajat");

                    b.HasIndex("IdAngajat");

                    b.ToTable("ProiecteAngajati");
                });

            modelBuilder.Entity("ProiectDAW.Models.angajati", b =>
                {
                    b.Property<int>("IdAngajat")
                        .HasColumnType("int");

                    b.Property<int>("ForeignKeyDepartamente")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salariu")
                        .HasColumnType("int");

                    b.HasKey("IdAngajat");

                    b.HasIndex("ForeignKeyDepartamente");

                    b.ToTable("angajati");
                });

            modelBuilder.Entity("ProiectDAW.Models.ProiecteAngajati", b =>
                {
                    b.HasOne("ProiectDAW.Models.angajati", "angajati")
                        .WithMany("ProiecteAngajati")
                        .HasForeignKey("IdAngajat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProiectDAW.Models.Proiecte", "Proiecte")
                        .WithMany("ProiecteAngajati")
                        .HasForeignKey("IdProiect")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("angajati");

                    b.Navigation("Proiecte");
                });

            modelBuilder.Entity("ProiectDAW.Models.angajati", b =>
                {
                    b.HasOne("ProiectDAW.Models.Departamente", "Departamente")
                        .WithMany("angajatis")
                        .HasForeignKey("ForeignKeyDepartamente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProiectDAW.Models.AdreseAngajati", "AdreseAngajati")
                        .WithOne("angajati")
                        .HasForeignKey("ProiectDAW.Models.angajati", "IdAngajat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdreseAngajati");

                    b.Navigation("Departamente");
                });

            modelBuilder.Entity("ProiectDAW.Models.AdreseAngajati", b =>
                {
                    b.Navigation("angajati");
                });

            modelBuilder.Entity("ProiectDAW.Models.Departamente", b =>
                {
                    b.Navigation("angajatis");
                });

            modelBuilder.Entity("ProiectDAW.Models.Proiecte", b =>
                {
                    b.Navigation("ProiecteAngajati");
                });

            modelBuilder.Entity("ProiectDAW.Models.angajati", b =>
                {
                    b.Navigation("ProiecteAngajati");
                });
#pragma warning restore 612, 618
        }
    }
}
